Flag SQL Injection attacks at TransferName
citizenwallet/indexer pull request #36
Opened 2024-03-11 22:00 UTC by pjol

Added a regexp check in the TransferName function to verify that contract addresses are correctly formatted and not malicious.

2024-03-12 13:23 UTC, kev-techi requested changes
All in all, looks good. Just a few comments.

2024-03-12 13:23 UTC, kev-techi commented on internal/events/handlers.go
> +		w.WriteHeader(http.StatusForbidden)
for a request response complaining about badly formatted parameters, I would return a 400 instead. Bad request makes more sense to me.

2024-03-12 13:23 UTC, kev-techi commented on internal/services/db/db.go
> +func (d *DB) TransferName(contract string) (string, bool) {
This should probably just return `errors.New("Bad contract address")`. And then we can do the standard:

```
name, err := d.TransferName(ev.Contract)
		if err  != nil {
			return err
		}
```

2024-03-12 13:23 UTC, kev-techi commented on internal/services/db/db.go
> +func (d *DB) TransferName(contract string) (string, bool) {
I would also suggest renaming this method to something that matches what it does (my fault for giving it a confusing name).

How about `TableNameSuffix`?

2024-03-13 15:26 UTC, closed without merging

2024-03-13 15:27 UTC, pjol commented
Continued at PR #38 Flagging SQL Injection at TableNameSuffix